
# Используем официальный образ .NET SDK для сборки приложения
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл проекта и восстанавливаем зависимости
COPY *.csproj ./
RUN dotnet restore

# Копируем остальные файлы и собираем приложение
COPY . ./
RUN dotnet publish -c Release -o out

# Используем официальный образ .NET Runtime для запуска приложения
FROM mcr.microsoft.com/dotnet/aspnet:6.0

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранное приложение из предыдущего шага
COPY --from=build /app/out .

# Указываем, какой исполняемый файл запускать
ENTRYPOINT ["dotnet", "lab4_quick.dll"] 
